import { createSuiteEnvelope,inchesToMm,mmToInches,parseSuiteProject,type SuiteEnvelope,type SuiteProject } from "@/lib/suite-contract";
import type { DrawItem,Point,SavedLayout } from "@/components/layout-planner";
const mmPoint=(point:Point)=>({x:inchesToMm(point.x),y:inchesToMm(point.y)});
const inchPoint=(point:{x:number;y:number})=>({x:mmToInches(point.x),y:mmToInches(point.y)});
export function layoutToSuite(layout:SavedLayout,organizationId:string|null=layout.suiteContext?.organizationId||null,buildrProjectId:string|null=layout.suiteContext?.buildrProjectId||null):SuiteEnvelope{
 const project:SuiteProject={id:layout.id,organizationId,buildrProjectId,importKey:`layout:${layout.id}`,name:layout.projectName,createdAt:new Date(layout.updatedAt).toISOString(),modifiedAt:new Date(layout.updatedAt).toISOString(),rooms:[{id:`room_${layout.id}`,name:layout.projectName,displayUnit:"ft-in",origin:{x:0,y:0},entities:[
  {id:`boundary_${layout.id}`,kind:"room.boundary",condition:"proposed",geometry:{vertices:layout.room.map(mmPoint)}},
  ...layout.items.map(item=>({id:item.id,kind:item.type==="wall"?"wall.interior":"opening",condition:"proposed" as const,geometry:{start:mmPoint(item.start),end:mmPoint(item.end),thickness:inchesToMm(item.thickness)}}))
 ],extensions:{layout:{tileWidthMm:inchesToMm(layout.tileWidth),tileHeightMm:inchesToMm(layout.tileHeight),groutMm:inchesToMm(layout.grout),appearance:layout.tileAppearance,wastePercent:layout.wastePercent,originMm:mmPoint(layout.origin),rotation:layout.rotation,showTile:layout.showTile}}}]};
 return createSuiteEnvelope(project,"layout","1.0.0",1);
}
export function suiteToLayout(input:unknown):{layout?:SavedLayout;error?:string;readOnly?:boolean;warning?:string}{
 const parsed=parseSuiteProject(input);if(!parsed.ok)return{error:parsed.error};const room=parsed.value.project.rooms[0];if(!room)return{error:"This shared project does not contain a room."};const boundary=room.entities.find(entity=>entity.kind==="room.boundary");const vertices=(boundary?.geometry as {vertices?:{x:number;y:number}[]})?.vertices;if(!vertices||vertices.length<3)return{error:"No compatible room boundary was found. The original shared record was not changed."};
 const imported=room.entities.filter(entity=>entity.kind==="wall.interior"||entity.kind==="opening").map(entity=>{const geometry=entity.geometry as {start:{x:number;y:number};end:{x:number;y:number};thickness?:number};return{id:entity.id,type:entity.kind==="opening"?"opening":"wall",start:inchPoint(geometry.start),end:inchPoint(geometry.end),thickness:mmToInches(geometry.thickness||114.3)} satisfies DrawItem});
 const settings=(room.extensions?.layout||{}) as {tileWidthMm?:number;tileHeightMm?:number;groutMm?:number;appearance?:SavedLayout["tileAppearance"];wastePercent?:number;originMm?:{x:number;y:number};rotation?:number;showTile?:boolean};const now=Date.now();return{readOnly:parsed.readOnly,warning:parsed.warning,layout:{id:parsed.value.project.id,updatedAt:now,projectName:parsed.value.project.name,room:vertices.map(inchPoint),items:imported,tileWidth:mmToInches(Number(settings.tileWidthMm||304.8)),tileHeight:mmToInches(Number(settings.tileHeightMm||609.6)),grout:mmToInches(Number(settings.groutMm||3.175)),materialUnit:"in",tileAppearance:settings.appearance||"transparent",wastePercent:Number(settings.wastePercent||10),wallThickness:4.5,origin:settings.originMm?inchPoint(settings.originMm):{x:0,y:0},rotation:settings.rotation===90?90:0,showTile:settings.showTile!==false,suiteContext:{organizationId:parsed.value.project.organizationId,buildrProjectId:parsed.value.project.buildrProjectId||null,importKey:parsed.value.project.importKey}}}
}
export function decodeSuiteHash(hash:string){try{const encoded=new URLSearchParams(hash.replace(/^#/,"")).get("suite");if(!encoded)return null;const binary=atob(decodeURIComponent(encoded));const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}catch{return null}}
export function suiteLink(base:string,envelope:SuiteEnvelope){const bytes=new TextEncoder().encode(JSON.stringify(envelope));let binary="";bytes.forEach(byte=>binary+=String.fromCharCode(byte));return `${base.replace(/\/$/,"")}/#suite=${encodeURIComponent(btoa(binary))}`}
export function downloadSuite(envelope:SuiteEnvelope,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(envelope,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()+".buildr.json";link.click();URL.revokeObjectURL(url)}
